///  PolygonMesh written by SKStudio.
/// 
return {
editinfo = "{\"gridchk\":true,\"bonechk\":true,\"rsetid\":\"legacy\",\"bndchk\":true}"
model64 = "U01ETAABAAAABAAAAWgAAQADKAAAAAAAAAAACTNzMh4/QAAAv0AAADNzMh4/QAAAP0AAAAAAAAAAAAAAAAAAALNzMh6/QAAAP0AAALNzMh6/QAAAv0AAADOiIWk/gAAAv4AAADOiIWk/gAAAP4AAALOiIWm/gAAAP4AAALOiIWm/gAAAv4AAAAEEAQMoAAAAABAAAAAJgAIAAAAAgAIAAAAAgAIAAAAAgAIAAAAAgAIAAAAAgAIAAAAAgAIAAAAAgAIAAAAAgAIAAAAAAgUBBCgAAAAAGAAAAAn///+A////gP////////+A////gP///wD///8A////AP///wAEAQACKAAAAAAgAAAACT8CDTA/pO2cPrpR6j+k7Zw+3zYoPsQuQD66Ueo/pO2cPwINMD+k7Zw/CDM5P8uOSj6uBdY/y45KPq4F1j/Ljko/CDM5P8uOSgAAAAABBAAAAwAAAEgAAAAkAAAAAgABAAMAAgAEAAQAAgAAAAUAAQAGAAUAAAABAAcABAAIAAcAAwAEAAgAAAAFAAgABAAAAAYAAwAHAAYAAQADAAEAAgADAAAAAAAAAAAAAAAAAAAAAAAA"
bnd = [0.0,0.0,0.0,0.0,1.0,1.0]

material = [
	{
		name = "square2"
		tec = "shading.basic"
		Ka = 0xFFFFFF00
		Kd = 0xFFFFFFFF
		Ks = 0x7F7F7F00
		Ke = 0x00000000
		shiness = 225.0
		cullface = SK_OFF
		texture0 = "../tex/square1.webp"
	}
]
}
