///  PolygonMesh converted by Blender.
/// 
return {
model64 = "U01ETAABAAAABAAABIgAAQADKAAAAAAAAAAAHT+AAAC/gAAAv4AAAD+AAAC/gAAAP4AAAAAAAAC/gAAAAAAAAL+AAAC/gAAAP4AAAL+AAAC/gAAAv4AAAD+AAAC/Kqqqv4AAAL+AAAC/Kqqqv4AAAL+AAAC+qqqqv4AAAD+AAAC+qqqqv4AAAD+AAAC/KqqqP4AAAD+AAAC/Kqqqv4AAAD+AAAC+qqqqv4AAAD+AAAC+qqqqP4AAAL+AAAC/KqqqP4AAAD+AAAC/KqqqP4AAAD+AAAC+qqqqP4AAAL+AAAC+qqqqP4AAAL+AAAC/Kqqqv4AAAL+AAAC/KqqqP4AAAL+AAAC+qqqqP4AAAL+AAAC+qqqqv4AAAL+AAAC/gAAAv4AAAL+AAAC/gAAAP4AAAL+AAAC/gAAAP4AAAD+AAAC/gAAAP4AAAD+AAAC/gAAAP4AAAD+AAAC/gAAAv4AAAD+AAAC/gAAAv4AAAL+AAAC/gAAAv4AAAAEEAQMoAAAAABAAAAAdAAB//wAAAAB//wAAAAB//wAAAAB//wAAAAB//wAAAAAAAH//AAAAAH//AAAAAH//AAAAAH//gAEAAAAAgAEAAAAAgAEAAAAAgAEAAAAAAAAAAIABAAAAAIABAAAAAIABAAAAAIABf/8AAAAAf/8AAAAAf/8AAAAAf/8AAAAAf/8AAAAAf/8AAAAAAAAAAIABAAAAAIABgAEAAAAAgAEAAAAAAAAAAH//AAAAAH//AgUBBCgAAAAAGAAAAB3/////////////////////////////////////////AP///wD//////////////wD///8A//////////////8A////AP//////////////AP///wD//////////////////////////////////////////wQBAAIoAAAAACAAAAAdP0AAAD7qlTA/QAAAPuqVMD7///4/mqVMPoAAAD7qlTA+gAAAPuqVMD9AAAA+VSpgPoAAAD5VKmA+gAAAvStWgD9AAAC9K1aAP0AAAD5VKmA/QAAAPlUqYD9AAAC9K1aAP0AAAL0rVoA+gAAAPlUqYD9AAAA+VSpgP0AAAL0rVoA+gAAAvStWgD6AAAA+VSpgPoAAAD5VKmA+gAAAvStWgD6AAAC9K1aAPoAAAD7qlTA+gAAAPuqVMD6AAAA+6pUwP0AAAD7qlTA/QAAAPuqVMD9AAAA+6pUwP0AAAD7qlTA+gAAAPuqVMAAAAAABBAAAAwAAAHgAAAA8AAAAAgABAAMAAgAEAAQAAgAAAAEAAgADAAUABwAGAAUACAAHAAkACwAKAAkADAALAA0ADwAOAA0AEAAPABEAEwASABEAFAATABUAEgAWABUAEQASABcADgAYABcADQAOABkACgAaABkACQAKABsABgAcABsABQAGAAAAAAAAAAAAAAAAAAAAAAAA"
bnd = [0.000000,-0.666667,0.000000,1.000000,0.333333,1.000000]

material = [
	{
		name = "wave_cube1"
		tec = "shading.basic"
		Ka = 0xffffff00
		Kd = 0xffffffff
		Ks = 0x7f7f7f00
		Ke = 0x00000000
		shiness = 225.000000
		texture0 = "../tex/wave_cube1.webp"
	}
]
}
